openapi: 3.0.0
info:
  title: Microsoft Graph API
  description: |
    This Swagger file describes the Microsoft Graph API endpoint for getting items from a list within a site.
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /sites/{site-id}/lists/{list-id}/items:
    get:
      summary: get items from a list
      description: |
        Get items from a specific list within a site.
      parameters:
        - name: site-id
          in: path
          description: The identifier of the site.
          required: true
          schema:
            type: string
        - name: list-id
          in: path
          description: The identifier of the list.
          required: true
          schema:
            type: string
        - name: $filter
          in: query
          description: | 
            A filter expression that limits the results based on a set of criteria.
            To search for items by Name or Title or Título use for example: $filter=fields/Title eq 'Smartphone'&$expand=fields.
            To search for items by Marca or Brand use for example: $filter=fields/Marca eq 'Apple'&$expand=fields.
            To search for items by their availability or status use for example: $filter=fields/Status eq 'Disponível'&$expand=fields.
            To search for items by location use for example: $filter=fields/Local eq 'HUB SP'&$expand=fields.
          schema:
            type: string
        - name: $expand
          in: query
          description: |
            "To be used for expanding the fields.
            For example: &$expand=fields"
          schema:
            type: string
        - name: $select
          in: query
          description: |
             A comma-separated list of properties to include in the response.
             For example, $select=fields/Title,fields/Status,fields/Marca,fields/Local,fields/id,fields/LinkTitleNoMenu,fields/LinkTitle.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
              example: |
                {
                  "value": [
                    {
                      "id": "1",
                      "fields": {
                        "Title": "Meta Quest",
                        "Status": "Emprestado",
                        "Marca": "Meta",
                        "Local": "Innovation Canter Recife",
                        "id": "1",
                        "LinkTitleNoMenu": "Meta Quest",
                        "LinkTitle": "Meta Quest",
                      }
                    },
                    {
                      "id": "2",
                      "fields": {
                        "Title": "Smartphone",
                        "Status": "Disponível",
                        "Marca": "Apple",
                        "Local": "HUB SP",
                        "id": "2",
                        "LinkTitleNoMenu": "Smartphone",
                        "LinkTitle": "Smartphone",
                      }
                    }
                  ]
                }
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
