openapi: 3.0.0
info:
  title: Microsoft Graph API
  description: |
    This Swagger file describes the Microsoft Graph API endpoint for getting items from a list within a site.
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /sites/{site-id}/lists/{list-id}/items:
    get:
      summary: get items from a list
      description: |
        Get items from a specific list within a site.
      parameters:
        - name: site-id
          in: path
          description: The identifier of the site.
          required: true
          schema:
            type: string
        - name: list-id
          in: path
          description: The identifier of the list.
          required: true
          schema:
            type: string
        - name: $filter
          in: query
          description: |
            A filter expression that limits the results based on a set of criteria.
            For example, $filter=fields/Title eq 'Test'.
          schema:
            type: string
        - name: $select
          in: query
          description: |
            A comma-separated list of properties to include in the response.
            For example, $select=fields/Title,fields/Description.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
              example: |
                {
                  "value": [
                    {
                      "id": "1",
                      "fields": {
                        "Title": "Item 1",
                        "Description": "This is item 1"
                      }
                    },
                    {
                      "id": "2",
                      "fields": {
                        "Title": "Item 2",
                        "Description": "This is item 2"
                      }
                    }
                  ]
                }
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
